lerex5/tr

app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/sellerActivity.java
app/src/main/res/layout/activity_seller.xml
app/src/main/res/values/attrs.xml

Added Full Screen Activity To Be modifies

App seller

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/pop.java
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_sell.xml
app/src/main/res/layout/addticket.xml

POP UP DIDNT WORK!!!

---

app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_sell.xml
app/src/main/res/layout/addticket.xml
app/src/main/res/values/strings.xml

Add The Remaining Buttons To enable basic functionality

Added PopUp Activity In sellActivity.java

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/addticket.xml
app/src/main/res/values/strings.xml

added the text view and an add button which on clicking closes popup

popup design

---

app/src/main/java/com/lerex/tr/sellActivity.java

Some Changes

---

app/build.gradle

Gradle Update

---

app/build.gradle
app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/SignupActivity.java

Login And Smart User Rememberance To Be Added

Added SignUp User Creation

---

app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/SignupActivity.java

Simple Email Auth

---

app/src/main/java/com/lerex/tr/sellActivity.java

Now Playing Movies Retrieved And Parsed from the themoviedb.org

Async Task Added To Parse Json

---

app/src/main/java/com/lerex/tr/sellActivity.java

Minor Comments#1

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_add_tickets.xml
app/src/main/res/values/strings.xml

Add tickets activity

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/ViewManager.java
app/src/main/java/com/lerex/tr/buyerActivity.java
app/src/main/res/layout/activity_buyer.xml
app/src/main/res/layout/activity_view_manager.xml
app/src/main/res/values/strings.xml

View manager

---

app/src/main/java/com/lerex/tr/sellActivity.java

Used JSON parsing on the Database

Retrieval Of Data and List Display

---

app/src/main/java/com/lerex/tr/buyerActivity.java
app/src/main/res/layout/activity_buyer.xml

Ticket Details

---

app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/MyListView.java
app/src/main/java/com/lerex/tr/TicketDetails.java
app/src/main/java/com/lerex/tr/ViewManager.java
app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/java/com/lerex/tr/buyerActivity.java
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_listview.xml
app/src/main/res/layout/list_seller.xml

Futhur Updations To Be Done Only In TicketDetails

Removed Redundant Ticket Definition Classes

---

.idea/misc.xml
app/src/main/java/com/lerex/tr/SellerListView.java
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_sell.xml
app/src/main/res/layout/list_seller.xml
app/src/main/res/values/dimens.xml

Converted Seller List View To RecyclerView

RecyclerView

---

.idea/misc.xml
app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/SignupActivity.java
app/src/main/res/layout/activity_buyer.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_signup.xml
app/src/main/res/values/strings.xml

Changed Authentication To Mobile Based

PhoneNumberAuthentication

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/ViewManBar.java
app/src/main/java/com/lerex/tr/ViewManager.java
app/src/main/java/com/lerex/tr/buyer1.java
app/src/main/res/drawable/ic_person.xml
app/src/main/res/layout/activity_buyer.xml
app/src/main/res/layout/activity_buyer1.xml
app/src/main/res/layout/activity_view_man_bar.xml
app/src/main/res/layout/activity_view_manager.xml
app/src/main/res/menu/btm_nav_bar.xml
app/src/main/res/values/strings.xml

Bottom Nav bar

---

app/build.gradle
app/google-services.json
app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/SignupActivity.java
app/src/main/java/com/lerex/tr/ViewManBar.java
app/src/main/java/com/lerex/tr/accountActivity.java
app/src/main/java/com/lerex/tr/buyer1.java
app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/activity_buyer1.xml
app/src/main/res/layout/activity_view_man_bar.xml
app/src/main/res/menu/btm_nav_bar.xml
app/src/main/res/values/strings.xml

changes to bottom nav bar

---

app/src/main/java/com/lerex/tr/FragHome.java

Retreving All Movies

---

app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/res/layout/activity_add_tickets.xml
app/src/main/res/values/styles.xml

Date Picker

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/BuyerListView.java
app/src/main/java/com/lerex/tr/SellerListView.java
app/src/main/java/com/lerex/tr/TicketDetails.java
app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/java/com/lerex/tr/buyerActivity.java
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_buyer.xml
app/src/main/res/layout/activity_listview.xml
app/src/main/res/layout/list_seller.xml
app/src/main/res/values/strings.xml

Deletion And Calling Added

---

app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/res/layout/activity_sell.xml

Validation

---

app/src/main/java/com/lerex/tr/AutoCompList.java
app/src/main/java/com/lerex/tr/CitiesJSON.java
app/src/main/java/com/lerex/tr/FragHome.java
app/src/main/java/com/lerex/tr/MainActivity.java
app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/java/com/lerex/tr/buyerActivity.java
app/src/main/res/layout/activity_add_tickets.xml
app/src/main/res/raw/cities.json
app/src/main/res/values/strings.xml

MinorChanges#6

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/FragHome.java
app/src/main/java/com/lerex/tr/StartActivity.java

All Prefetch done only in Start Activity

Manifest Correction

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/LocationActivity.java
app/src/main/java/com/lerex/tr/SignupActivity.java
app/src/main/java/com/lerex/tr/StartActivity.java
app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/java/com/lerex/tr/buyerActivity.java
app/src/main/java/com/lerex/tr/sellActivity.java
app/src/main/res/layout/activity_add_tickets.xml
app/src/main/res/layout/activity_buyer.xml
app/src/main/res/layout/activity_location.xml
app/src/main/res/layout/activity_sell.xml

Geo Location Sensing To Be Added

Location Selection

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/lerex/tr/LocationActivity.java
app/src/main/java/com/lerex/tr/StartActivity.java
app/src/main/java/com/lerex/tr/accountActivity.java

Start Activity Minor Changes

---

app/src/main/java/com/lerex/tr/SellerListView.java
app/src/main/java/com/lerex/tr/accountActivity.java
app/src/main/res/layout/list_seller.xml

ListViewSpacing to be added through item decors and account view to be reworked

MinorChanges

---

app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/res/layout/activity_add_tickets.xml
app/src/main/res/values/strings.xml

TimePicker

---

app/src/main/java/com/lerex/tr/SellerListView.java
app/src/main/java/com/lerex/tr/TicketDetails.java
app/src/main/java/com/lerex/tr/addTickets.java
app/src/main/res/layout/activity_add_tickets.xml
app/src/main/res/layout/list_seller.xml

EventTimeAdded
